name: Aliyun Deployment Pipeline

on:
  push:
    branches:
      - aliyun
      - aliyun-canary

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./hello

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Aliyun
      - name: Faasit deploy to Aliyun (Production)
        if: github.ref == 'refs/heads/aliyun'
        env:
          FAASIT_SECRET_ALIYUN_ACCESS_KEY_ID: ${{ secrets.FAASIT_SECRET_ALIYUN_ACCESS_KEY_ID }}
          FAASIT_SECRET_ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.FAASIT_SECRET_ALIYUN_ACCESS_KEY_SECRET }}
          FAASIT_SECRET_ALIYUN_REGION: ${{ secrets.FAASIT_SECRET_ALIYUN_REGION }}
          FAASIT_SECRET_ALIYUN_ACCOUNT_ID: ${{ secrets.FAASIT_SECRET_ALIYUN_ACCOUNT_ID }}
        run: ft deploy -p aliyun

      # TODO: Aliyun (Canary)
      - name: Faasit deploy to Aliyun (Canary)
        if: github.ref == 'refs/heads/aliyun-canary'
        env:
          FAASIT_SECRET_ALIYUN_ACCESS_KEY_ID: ${{ secrets.FAASIT_SECRET_ALIYUN_ACCESS_KEY_ID }}
          FAASIT_SECRET_ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.FAASIT_SECRET_ALIYUN_ACCESS_KEY_SECRET }}
          FAASIT_SECRET_ALIYUN_REGION: ${{ secrets.FAASIT_SECRET_ALIYUN_REGION }}
          FAASIT_SECRET_ALIYUN_ACCOUNT_ID: ${{ secrets.FAASIT_SECRET_ALIYUN_ACCOUNT_ID }}
        run: ft deploy -p aliyun
