name: Aliyun Deployment Pipeline

on:
  push:
    branches:
      - aliyun
      - aliyun-canary

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./hello

    env:
      FAASIT_SECRET_ALIYUN_ACCESS_KEY_ID: ${{ secrets.FAASIT_SECRET_ALIYUN_ACCESS_KEY_ID }}
      FAASIT_SECRET_ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.FAASIT_SECRET_ALIYUN_ACCESS_KEY_SECRET }}
      FAASIT_SECRET_ALIYUN_REGION: ${{ secrets.FAASIT_SECRET_ALIYUN_REGION }}
      FAASIT_SECRET_ALIYUN_ACCOUNT_ID: ${{ secrets.FAASIT_SECRET_ALIYUN_ACCOUNT_ID }}
      ALIBABA_CLOUD_OSS_BUCKET_NAME: ${{ secrets.ALIBABA_CLOUD_OSS_BUCKET_NAME }}
      ALIBABA_CLOUD_OSS_REGION: ${{ secrets.ALIBABA_CLOUD_OSS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Production
      - name: Faasit deploy to Aliyun (Production)
        if: github.ref == 'refs/heads/aliyun'
        run: ft deploy -p aliyun

      - name: Invoke Aliyun Function (Production)
        if: github.ref == 'refs/heads/aliyun'
        run: sleep 3 && ft invoke -p aliyun

      # Canary
      - name: Faasit deploy to Aliyun (Canary)
        if: github.ref == 'refs/heads/aliyun-canary'
        run: ft deploy -p aliyun --canary

      - name: Invoke Aliyun Function (Canary)
        if: github.ref == 'refs/heads/aliyun-canary'
        run: sleep 3 && ft invoke -p aliyun --canary
