name: K8s Deployment Pipeline

on:
  push:
    branches:
      - k8s
      - k8s-canary

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./hello

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # K8s
      - name: Faasit deploy to k8s (Production)
        if: github.ref == 'refs/heads/k8s'
        run: ft deploy -p k8s

      # K8s (Canary)
      - name: Faasit deploy to K8s (Canary)
        if: github.ref == 'refs/heads/k8s-canary'
        run: ft deploy -p k8s --canary
