name: K8s Deployment Pipeline

on:
  push:
    branches:
      - k8s
      - k8s-canary

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./hello

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean old deployment
        run: kubectl delete ksvc helloapp-hello --ignore-not-found && kubectl delete pods --force --all && kubectl delete svc --all

      # K8s
      - name: Build image (Production)
        if: github.ref == 'refs/heads/k8s'
        run: ft build -p k8s

      - name: Faasit deploy to k8s (Production)
        if: github.ref == 'refs/heads/k8s'
        run: ft deploy -p k8s

      - name: Invoke k8s Function (Production)
        if: github.ref == 'refs/heads/k8s'
        run: ft invoke -p k8s

      # K8s (Canary)
      - name: Build image (Canary)
        if: github.ref == 'refs/heads/k8s-canary'
        run: ft build -p k8s --canary

      - name: Faasit deploy to K8s (Canary)
        if: github.ref == 'refs/heads/k8s-canary'
        run: ft deploy -p k8s --canary

      - name: Invoke k8s Function (Canary)
        if: github.ref == 'refs/heads/k8s-canary'
        run: ft invoke -p k8s --canary
