name: Knative Deployment Pipeline

on:
  push:
    branches:
      - knative
      - knative-canary

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./hello

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean old deployment
        run: kubectl delete svc helloapp-hello pod helloapp-hello ksvc helloapp-hello --ignore-not-found

      # Knative
      - name: Build image (Production)
        if: github.ref == 'refs/heads/knative'
        run: ft build -p knative

      - name: Faasit deploy to Knative (Production)
        if: github.ref == 'refs/heads/knative'
        run: ft deploy -p knative

      - name: Invoke knative Function (Production)
        if: github.ref == 'refs/heads/knative'
        run: ft invoke -p knative


      # Knative (Canary)
      - name: Faasit deploy to Knative (Canary)
        if: github.ref == 'refs/heads/knative-canary'
        run: ft build -p knative --canary

      - name: Faasit deploy to Knative (Canary)
        if: github.ref == 'refs/heads/k8s-canary'
        run: ft deploy -p knative --canary

      - name: Invoke k8s Function (Canary)
        if: github.ref == 'refs/heads/k8s-canary'
        run: ft invoke -p knative --canary