name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./demo-chammeleon
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: taiki-e/checkout-action@v1

      - name: Faasit build
        run: ft build
        
      - name: Faasit deploy
        run: ft deploy
