name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Faasit deploy
        run: ft deploy
