name: Multi-Environment Deployment Pipeline

on:
  push:
    branches:
      - multi-env

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./hello

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean old deployment
        run: kubectl delete svc helloapp-hello pod helloapp-hello ksvc helloapp-hello --ignore-not-found

      - name: Aliyun (Multi-env)
        env:
          FAASIT_SECRET_ALIYUN_ACCESS_KEY_ID: ${{ secrets.FAASIT_SECRET_ALIYUN_ACCESS_KEY_ID }}
          FAASIT_SECRET_ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.FAASIT_SECRET_ALIYUN_ACCESS_KEY_SECRET }}
          FAASIT_SECRET_ALIYUN_REGION: ${{ secrets.FAASIT_SECRET_ALIYUN_REGION }}
          FAASIT_SECRET_ALIYUN_ACCOUNT_ID: ${{ secrets.FAASIT_SECRET_ALIYUN_ACCOUNT_ID }}
          ALIBABA_CLOUD_OSS_BUCKET_NAME: ${{ secrets.ALIBABA_CLOUD_OSS_BUCKET_NAME }}
          ALIBABA_CLOUD_OSS_REGION: ${{ secrets.ALIBABA_CLOUD_OSS_REGION }}
        run: ft deploy -p aliyun && ft invoke -p aliyun

      - name: Knative (Multi-env)
        run: ft build -p knative && ft deploy -p knative
